### PR TITLE
Bump React peer dependency to v16

### PR DESCRIPTION
**Pull request by feimosi**
I've been using `react-twitter-auth` with `react@16` for a month now, without any issues.

### CODE REVIEW

**Comment by ivanvs** [comment]
Hi @feimosi,

Thank you for you contribution. I will do some testing and merge it.

**Comment by feimosi** [comment]
Any updates?

**Comment by feimosi** [comment]
Any updates? I still haven't encountered any problems with the latest React. Already using it in production.

**Comment by ivanvs** [comment]
I am currently on vacation. During December and January I had too much obligations, so I haven't finished this. Sorry :(

I have some concerns about backword compatibility. Will check that when I get back from vacation.

**Comment by ivanvs** [comment]
If I accept your change then this package will stop working with projects that have react 15.5.x. But will work with 16.6.3. I looked at [npm](http://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html) documentation. It seems that both case would work if we would rewrite this:
```
  "peerDependencies": {
    "react": ">=15.5.0",
    "react-dom": ">=15.5.0",
    "prop-types": ">=15.5.0"
  },
```

What do you think about that?

**Comment by feimosi** [comment]
My bad, you're totally right. I forgot about backwards compatibility. Actually you can use a range to make sure it won't break with React v17:

```
 "peerDependencies": {
    "react": "> 15.5.0 < 17",
    "react-dom": "> 15.5.0 < 17",
    "prop-types": "> 15.5.0 < 17"
  },
```

Tested at https://semver.npmjs.com

**Comment by ivanvs** [comment]
Ok, cool. I am totally fine with this changes. Can you push that changes so I could merge them into master?

**Comment by feimosi** [comment]
Done, you can squash these two commits while merging.

**Pull request merged**
